ChequeMvc/Models/ErrorViewModel.cs
using System;

namespace ChequeMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChequeMvc/Controllers/ChequeController.cs
using ChequeMvc.Entities;
using ChequeMvc.Services.Shared.Utilities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;

namespace ChequeMvc.Controllers
{
    public class ChequeController : Controller
    {
        private IChequeUtilities _chequeUtilities;

        /// <summary>
        /// Public constructor.
        /// Inject IChequeUtilities.
        /// IChequeUtilities is registered as a service in Startup.cs
        /// </summary>
        /// <param name="chequeUtilities"></param>
        public ChequeController(IChequeUtilities chequeUtilities)
        {
            _chequeUtilities = chequeUtilities;
        }

        /// <summary>
        /// GET: Cheque/Create
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: Cheque/Create
        /// </summary>
        /// <param name="cheque"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ChequeEntity cheque)
        {
            if (ModelState.IsValid)
            {
                // Serialize object to a string and store in TempData
                var serializedObject = JsonConvert.SerializeObject(cheque);
                TempData["cheque"] = serializedObject;

                return RedirectToAction("Show", "cheque");
            }

            return View();
        }

        /// <summary>
        /// Show cheque issued
        /// </summary>
        /// <returns></returns>
        public ActionResult Show()
        {
            if (TempData["cheque"] is string serializedObject)
            {
                // Deserialize object and store as ChequeEntity
                var cheque = JsonConvert.DeserializeObject<ChequeEntity>(serializedObject);
                ViewData["chequePayee"] = cheque.chequePayee;
                ViewData["chequeAmount"] = ((decimal)cheque.chequeAmount).ToString("#,##0.00");
                ViewData["amountInWords"] = _chequeUtilities.TranslateDollarAmountToWords(cheque.chequeAmount);
                ViewData["chequeDate"] = ((DateTime)cheque.chequeDate).ToString("dd/MM/yyyy");
            }

            return View();
        }
    }
}

ChequeMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChequeMvc.Models;

namespace ChequeMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChequeMvc/Views/Cheque/Create.cshtml
@model ChequeMvc.Entities.ChequeEntity

@{
    ViewData["Title"] = "Issue Cheque";
}

<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.chequePayee, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.chequePayee, new { htmlAttributes = new { @class = "form-control", placeholder = "Cheque payee" } })
            </div>
            <div class="cold-md-4">
                @Html.ValidationMessageFor(model => model.chequePayee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chequeAmount, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.chequeAmount, new { htmlAttributes = new { @class = "form-control", placeholder = "Cheque amount" } })
            </div>
            <div class="col-md-8">
                @Html.ValidationMessageFor(model => model.chequeAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chequeDate, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.chequeDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Cheque date" } })
            </div>
            <div class="col-md-9">
                @Html.ValidationMessageFor(model => model.chequeDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ChequeMvc/Views/Cheque/Show.cshtml
@{
    ViewData["Title"] = "Show Cheque";
}

<style>
    .chequeBackGround {
        background: #e9f6fd;
        background: -moz-linear-gradient(top, #e9f6fd 0%, #d3eefb 100%);
        background: -webkit-linear-gradient(top, #e9f6fd 0%,#d3eefb 100%);
        background: linear-gradient(to bottom, #e9f6fd 0%,#d3eefb 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e9f6fd', endColorstr='#d3eefb',GradientType=0 );
    }
</style>

<h2>@ViewData["Title"]</h2>

<div class="row table-bordered chequeBackGround" style="border-color: blue">
    <div style="margin-bottom: 0">
        <div class="col-sm-10">
            <h2 style="margin-bottom: 0">MODEL-VIEW-CONTROLLER BANK</h2>
            <h5 style="margin-top: 0">1 MVC Way Branch</h5>
        </div>
        <div class="col-sm-2 text-right">
            <h5>01-02-03</h5>
        </div>
    </div>
    <hr>
    <div style="margin-top: 0">
        <div class="col-sm-10">
            <h5 style="margin-bottom: 0">Pay to</h5>
            <h3 style="margin-top: 0; font-variant: small-caps">@ViewData["chequePayee"]</h3>
        </div>
        <div class="col-sm-2 text-right">
            <h5 style="margin-bottom: 0">Date</h5>
            <h3 style="margin-top: 0">@ViewData["chequeDate"]</h3>
        </div>
    </div>
    <div style="margin-top: 0">
        <div class="col-sm-9">
            <h5 style="margin-bottom: 0">The amount of</h5>
            <h3 style="margin-top: 0; font-variant: small-caps">@ViewData["amountInWords"]</h3>
        </div>
        <div class="col-sm-3 text-right">
            <h5 style="margin-bottom: 0">&nbsp;</h5>
            <h3 style="margin-top: 0">$@ViewData["chequeamount"]</h3>
        </div>
    </div>
    <div>
        <div class="col-sm-6"></div>
        <div class="col-sm-6 text-right">
            <br /><br />
            <div style="border-bottom: 1px dotted blue">
                <h3 class="text-center" style="font-family: 'Segoe Script'; font-weight: bold; color: blue">Zaldy De Leon</h3>
            </div>
            <br />
        </div>
    </div>
    <div>
        <div class="col-sm-4">
            <h6 style="margin-bottom: 0">Cheque number</h6>
            <h5 style="margin-top: 0">00123456</h5>
        </div>
        <div class="col-sm-4 text-center">
            <h6 style="margin-bottom: 0">Branch code</h6>
            <h5 style="margin-top: 0">000-001</h5>
        </div>
        <div class="col-sm-4 text-right">
            <h6 style="margin-bottom: 0">Account number</h6>
            <h5 style="margin-top: 0">000-001-987654321</h5>
        </div>
    </div>
</div>

ChequeMvc/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ChequeMvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ChequeMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ChequeMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChequeMvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ChequeMvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Cheque" asp-action="Create">Issue Cheque</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ChequeMvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>